### ISSUE TITLE
How can I specify the version to install?

### ISSUE THREAD

**Issue by m4l490n** [a-langer/eclipse-oomph-console#3]
Hello, thanks for the project! I have a question. How can I specify the version I want to install? For example, I need 2022-03 and I did this:

`./eclipse-inst -nosplash -application org.eclipse.oomph.console.application -vmargs -Doomph.installation.location="$PWD/eclipse" -Doomph.product.id="epp.package.cdt:2022-03"`

But it didn't work. Also, is this even possible?

**Comment by a-langer** [comment]
Hello, the error log shows a list of available products, among which there is no "epp.package.cdt", but there is "epp.package.cpp", I think this is what you need:

```bash
./eclipse-inst -nosplash -application org.eclipse.oomph.console.application -vmargs \
-Doomph.installation.location="$PWD/eclipse" \
-Doomph.product.id="epp.package.cpp:2022-03" 
```

As for "cdt", it is in the list of projects (see [CDT.setup](https://raw.githubusercontent.com/eclipse-cdt/cdt/main/releng/CDT.setup)), as far as I understand, it contains the sources of the CDT itself, but you can try installing it too:

```bash
./eclipse-inst -nosplash -application org.eclipse.oomph.console.application -vmargs \
-Doomph.installation.location="$PWD/eclipse" \
-Doomph.product.id="epp.package.cpp:2022-03" \
-Doomph.project.id="cdt:main"
```
