### ISSUE TITLE
Oomph fails to connect to eclipse download hosts

### ISSUE THREAD

**Issue by manumaan** [a-langer/eclipse-oomph-console#5]
Gets stuck at 74%. Error says connection refused. But from same host i can access the URLs given in errors. This is inside a Ubuntu 22.04 docker container. 

!MESSAGE Connection to https://download.eclipse.org/releases/2023-03/202301131000/p2.index failed on Connect to https://download.eclipse.org:443 [download.eclipse.org/198.41.30.199] failed: Connection refused

!MESSAGE Connection to https://download.eclipse.org/oomph/updates/milestone/latest/compositeContent.jar failed on Connect to https://download.eclipse.org:443 [download.eclipse.org/198.41.30.199] failed: Connection refused. Retry attempt 0 started

!MESSAGE Connection to https://download.eclipse.org/oomph/updates/milestone/latest/compositeArtifacts.jar failed on Connect to https://download.eclipse.org:443 [download.eclipse.org/198.41.30.199] failed: Connection refused. Retry attempt 0 started

!MESSAGE Connection to https://download.eclipse.org/technology/epp/packages/2023-03/202301121200/features/org.eclipse.epp.package.common.feature_4.27.0.20230112-0751.jar failed on Connect to https://download.eclipse.org:443 [download.eclipse.org/198.41.30.199] failed: Connection refused. Retry attempt 0 started

!MESSAGE Connection to https://download.eclipse.org/technology/epp/packages/2023-03/202301121200/features/org.eclipse.epp.package.java.feature_4.27.0.20230112-0751.jar failed on Connect to https://download.eclipse.org:443 [download.eclipse.org/198.41.30.199] failed: Connection refused. Retry attempt 0 started

!MESSAGE Failure reporting download statistics to URL: https://download.eclipse.org/stats/technology/epp/packages/2023-03-M1/org.eclipse.epp.package.common/4.27.0.20230112-0751

!MESSAGE Unable to connect to repository https://download.eclipse.org/stats/technology/epp/packages/2023-03-M1/org.eclipse.epp.package.common/4.27.0.20230112-0751

!MESSAGE Connection to https://eclipse.mirror.rafal.ca/releases/2023-03/202301131000/plugins/org.eclipse.mylyn.wikitext.asciidoc.ui_3.0.42.202201072301.jar failed on Connect to https://eclipse.mirror.rafal.ca:443 [eclipse.mirror.rafal.ca/207.210.46.249] failed: Connection refused. Retry attempt 0 started

[issue.txt](https://github.com/a-langer/eclipse-oomph-console/files/10555924/issue.txt)

**Comment by a-langer** [comment]
I would recommend adding some tweaks.
Increase connection and read timeouts:

```bash
-Doomph.setup.ecf.connect.timeout=90000
-Doomph.setup.ecf.read.timeout=90000
```

Make sure you don't use mirrors:

```bash
-Declipse.p2.mirrors=false
```

Increase the number of connection retries:

```bash
-Doomph.p2.repository.retry=2
```

Disable check of public key certificates (e.g. self-signed ones):

```
-Doomph.installer.ssl.insecure=true
```

**Comment by a-langer** [comment]
Also, for diagnostics, you can enable ECF debugging:

```bash
-Doomph.setup.ecf.trace=true
```

**Comment by manumaan** [comment]
[eclipse.log](https://github.com/a-langer/eclipse-oomph-console/files/10564664/eclipse.log)
Same results again. Below is the command i ran. 

./eclipse-inst -nosplash -application org.eclipse.oomph.console.application -vmargs -Doomph.installation.location="$PWD/ide" -Doomph.product.id="epp.package.java" -Doomph.setup.ecf.connect.timeout=90000 -Doomph.setup.ecf.read.timeout=90000 -Declipse.p2.mirrors=false -Doomph.p2.repository.retry=2 -Doomph.installer.ssl.insecure=true -Doomph.setup.ecf.trace=true

**Comment by a-langer** [comment]
I don't see ECF debugging in this log. Try adding "oomph.installer.verbose=true" and and send the output to a file:

```
./eclipse-inst -nosplash -application org.eclipse.oomph.console.application -vmargs \
-Doomph.installation.location="$PWD/ide" -Doomph.product.id="epp.package.java" \
-Doomph.setup.ecf.connect.timeout=90000 \
-Doomph.setup.ecf.read.timeout=90000 \
-Declipse.p2.mirrors=false \
-Doomph.p2.repository.retry=2 \
-Doomph.installer.ssl.insecure=true \
-Doomph.setup.ecf.trace=true \
-Doomph.installer.verbose=true 2>&1 | tee "eclipse.log"
```

If the error only reproduces in a container, then install without a container and compare the two logs. The difference between the logs will show at what stage the error occurs. 
At the moment it all boils down to a network stack error inside the Docker container. I would recommend checking the [DNS](https://docs.docker.com/config/containers/container-networking/#dns-services) and proxy settings inside the container.
